---
apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    env: simple-app
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: simple-app-ctr
    ports:
    - containerPort: 8080
    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: svc-simple-app
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    env: simple-app