---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt
 namespace: cert-manager
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory    #### <<<< change for prod: https://acme-v02.api.letsencrypt.org/directory
   email: nataraj.ramamoorthy13@gmail.com #### <<<< Your email
   privateKeySecretRef:
     name: letsencrypt
   solvers:
   - http01:
       ingress:
         class:  nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
  namespace: cert-manager
spec:
  secretName: letsencrypt
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: demo.robofarming.link #### <<<< Add your own domain name
  dnsNames:
  - demo.robofarming.link #### <<<< Add your own domain name
  
